### ISSUE TITLE
nginx_status need to grab for different spelling of "nginx"

### ISSUE THREAD

**Issue by heckpet** [jleggat/check_mk-plugins#1]
On my Debian Wheezy system (3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux) I experienced the fact, that after NGINX restart, the netstat command used in the script sometimes shows the following output:

24372/nginx: worker

While the check in line 42 only looks for "nginx" without the colon, the checks returns zero value.

After restart of NGINX, the value then returns to :+1: 

29561/nginx

Suggest to look at both values (nginx and nginx:)

Peter

**Comment by onecooltaco** [comment]
Commit 073c9f3a542a67e0ba152aa1eb98fe336111200d strips a trailing ":" from the process name.

I don't have a system to replicate this issue on.  Please let me know if this works.

Thanks,
jeremy

**Comment by onecooltaco** [comment]
Fixed with 506445c0a088fefdeacf49ef188cdf4b05e5201d .  It now that is strips from the right side to get the process name.
